server:
  port: 9090
  
spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descripter:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG