server:
  port: 9090
  
spring:
  jpa:
    defer-datasource-initialization: true
    properties:      
      hibernate:
        format_sql: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE