--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (1, '홍길동', 'hong@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('홍길동', 'hong@tjoeun.com', now(), now());
--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (2, '임꺽정', 'lim@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('임꺽정', 'lim@tjoeun.com', now(), now());
--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (3, '장길산', 'jang@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('장길산', 'jang@tjoeun.com', now(), now());
--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (4, '일지매', 'il@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('일지매', 'il@tjoeun.com', now(), now());
--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (5, '홍길동', 'gildong@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('홍길동', 'gildong@tjoeun.com', now(), now());
--call next value for hibernate_sequence;
--INSERT INTO member(id, name, email, create_at, update_at) VALUES (6, '홍길동', 'hong@tjoeun.com', now(), now());
INSERT INTO member(name, email, create_at, update_at) VALUES ('홍길동', 'hong@tjoeun.com', now(), now());